version: '3'

services:
  postgres:
    image: postgres:16.4
    environment:
      TZ: 'America/Sao_Paulo'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    image: nginx:1.24
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
  app:
    image: dauid64/api-blog-facilitando-bits
    build:
      context: .
    volumes:
      - ./staticroot:/staticroot/
      - ./media:/media/
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
