services:
  postgres:
    image: postgres:16.4
    env_file:
      - .env
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  nginx:
    image: nginx:1.24
    ports:
      - 8080:8080
    volumes:
      - ./nginx:/etc/nginx/conf.d
