# Generated by Django 5.1.4 on 2025-01-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_content_remove_article_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='language',
        ),
    ]
